name: pixeldeep1
favicon: null
layout_spectrum: 0.36824
typography_spectrum: 0.14212
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9aa7af'
    - '#ce4123'
    - '#56555a'
    - '#16dffd'
    - '#fe7966'
  brandStrength: 0.8125
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
