title: PD
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: 'Design, Social & Advertising.'
color:
  saturation: 0.9375
  brandStrength: 0.0625
  rhythmicContrast: 0.5
  brandColors:
    - '#9aa7af'
    - '#ce4123'
    - '#56555a'
    - '#16dffd'
    - '#fe7966'
  lightness: 0.6875
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Click Here
    id: b4991e04-c513-406f-9436-acd9e1dbb59f
    type: content
favicon: null
name: pixeldeep1
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.14212
layout_spectrum: 0.3691756
